In [1]:
import pandas as pd

In [2]:
Data=pd.read_csv('Women_Safety_Risk_Analysis.csv')

In [ ]:
Data

              State  Population  Rape Cases  Year  Kidnapping Cases
0    Andhra Pradesh    49577103         971  2018              1833
1    Andhra Pradesh    49577103        1086  2019               902
2    Andhra Pradesh    49577103        1095  2020               737
3    Andhra Pradesh    49577103        1188  2021               835
4    Andhra Pradesh    49577103         621  2022               903
..              ...         ...         ...   ...               ...
135     West Bengal    91276115        1069  2018              8339
136     West Bengal    91276115        1069  2019              5190
137     West Bengal    91276115        1128  2020              9309
138     West Bengal    91276115        1123  2021              8339
139     West Bengal    91276115        1111  2022              8088

[140 rows x 5 columns]

### Feature Creation

1. Rape rate per lakh population
- **Rape_rate = (Rape Cases / Population) * 100000**

In [4]:
Data['Rape_rate'] = (Data['Rape Cases']/ Data['Population']) * 100000

2. Kidnapping Rate 
- **Kidnap_rate = (Kidnapping Cases / Population) * 100000**

In [5]:
Data['Kidnap_rate'] = (Data['Kidnapping Cases'] / Data['Population']) * 100000

- Normalization ( convert data in a fixed range eg : 1-10 )         
df['norm_0_10'] = ( 
    (df['col'] - df['col'].min()) / (df['col'].max() - df['col'].min())
) * 10

3. Rape_norm
4. kidnap_norm

In [6]:
Data['Rape_norm'] = (
    (Data['Rape_rate'] - Data['Rape_rate'].min()) /
    (Data['Rape_rate'].max() -Data['Rape_rate'].min())
) * 10

Data['Kidnap_norm'] = (
    (Data['Kidnap_rate'] - Data['Kidnap_rate'].min()) /
    (Data['Kidnap_rate'].max() - Data['Kidnap_rate'].min())
) * 10

In [8]:
Data.head(3)

,State,Population,Rape Cases,Year,Kidnapping Cases,Rape_rate,Kidnap_rate,Rape_norm,Kidnap_norm
0,Andhra Pradesh,49577103,971,2018,1833,1.958565,3.697271,1.942399,1.169983
1,Andhra Pradesh,49577103,1086,2019,902,2.190527,1.819388,2.198927,0.544920
2,Andhra Pradesh,49577103,1095,2020,737,2.208681,1.486573,2.219003,0.434141

In [9]:
Data.to_csv("Women_Safety_Risk_Analysis_FE.csv", index=False)